version: '3'

services:
    app-mycontacts:
        build: .
        tty: true
        ports:
            - "3001:3001"
        volumes:
            - .:/usr/app
        networks:
            - app-network
        depends_on: 
            - db-mycontacts
    db-mycontacts:
        image: postgres
        restart: always
        tty: true
        volumes:
            - ./.docker/data:/var/lib/postgres/data
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        ports:
            - "5432:5432"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge