version: '3'

services:
    mycontacts-db:
        image: postgres
        container_name: mycontacts-db
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - postgres_mycontacts_data:/var/lib/postgresql/data
    mycontacts-node:
        build: .
        container_name: mycontacts-node
        restart: always
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        depends_on:
            - mycontacts-db
        volumes:
            - .:/usr/myContacts-node
        command: npm run dev
volumes:
    postgres_mycontacts_data: